language: csharp
sudo: required
dist: trusty
mono: none
dotnet: 1.0.1
install:
 - export DOTNET_CLI_TELEMETRY_OUTPUT=1
before_script:
 - npm install -g gulp-cli gulp
 - chmod a+x ./build.sh
script:
 - ./build.sh --quiet verify